#ifndef _BERT_REGEX_H_
#define _BERT_REGEX_H_

#if defined(BERT_PCRE)

#include <pcre.h>

#define BERT_REGEX_UNICODE		PCRE_UNICODE
#define BERT_REGEX_ANCHORED		PCRE_ANCHORED
#define BERT_REGEX_CASELESS		PCRE_CASELESS
#define BERT_REGEX_DOLLAR_ENDONLY	PCRE_DOLLAR_ENDONLY
#define BERT_REGEX_DOTALL		PCRE_DOTALL
#define BERT_REGEX_EXTENDED		PCRE_EXTENDED
#define BERT_REGEX_FIRSTLINE		PCRE_FIRSTLINE
#define BERT_REGEX_MULTILINE		PCRE_MULTILINE
#define BERT_REGEX_NO_AUTO_CAPTURE	PCRE_NO_AUTO_CAPTURE
#define BERT_REGEX_DUPNAMES		PCRE_DUPNAMES
#define BERT_REGEX_UNGREEDY		PCRE_UNGREEDY
#define BERT_REGEX_NEWLINE_CR		PCRE_NEWLINE_CR
#define BERT_REGEX_NEWLINE_LF		PCRE_NEWLINE_LF
#define BERT_REGEX_NEWLINE_CRLF		PCRE_NEWLINE_CRLF
#define BERT_REGEX_NEWLINE_ANYCRLF	PCRE_NEWLINE_ANYCRLF
#define BERT_REGEX_NEWLINE_ANY		PCRE_NEWLINE_ANY
#define BERT_REGEX_BSR_ANYCRLF		PCRE_BSR_ANYCRLF
#define BERT_REGEX_BSR_UNICODE		PCRE_BSR_UNICODE

#else

// sneakily copied from pcre.h of libpcre-7.9.
#define BERT_REGEX_UNICODE		0x00000800
#define BERT_REGEX_ANCHORED		0x00000010
#define BERT_REGEX_CASELESS		0x00000001
#define BERT_REGEX_DOLLAR_ENDONLY	0x00000020
#define BERT_REGEX_DOTALL		0x00000004
#define BERT_REGEX_EXTENDED		0x00000008
#define BERT_REGEX_FIRSTLINE		0x00040000
#define BERT_REGEX_MULTILINE		0x00000002
#define BERT_REGEX_NO_AUTO_CAPTURE	0x00001000
#define BERT_REGEX_DUPNAMES		0x00080000
#define BERT_REGEX_UNGREEDY		0x00000200
#define BERT_REGEX_NEWLINE_CR		0x00100000
#define BERT_REGEX_NEWLINE_LF		0x00200000
#define BERT_REGEX_NEWLINE_CRLF		0x00300000
#define BERT_REGEX_NEWLINE_ANYCRLF	0x00500000
#define BERT_REGEX_NEWLINE_ANY		0x00400000
#define BERT_REGEX_BSR_ANYCRLF		0x00800000
#define BERT_REGEX_BSR_UNICODE		0x01000000

#endif

#endif
